### PR TITLE
Added support for single channel inputs for CoreAudio

### PR DESCRIPTION
**Pull request by marcelofg55**

### CODE REVIEW

**Comment by marcelofg55** [comment]
Don't merge yet :)

**Comment by SaracenOne** [comment]
Yeah, I just want to confirm, because I know if it's doing it, the part of the code responsible for copying the microphone input to the buffer, even if there's only one channel of audio coming through, it needs to make sure that it is always converted to two channels, since that's what the stream expects.

**Comment by marcelofg55** [comment]
Just updated it, I don't have a single mic device but code should be good.

**Comment by SaracenOne** [comment]
@marcelofg55 Unfortunately I can't test this, but it still doesn't look like it's correctly handling single channel audio. Go look at my code in the WASAPI driver to see how it's set up. It has special case handling for single channel audio where it converts it into stereo audio, which is what the AudioStreamMicrophone is trying to parse.

**Comment by marcelofg55** [comment]
Did you check the last update I made?

```
		for (int i = 0; i < inNumberFrames * ad->capture_channels; i++) {
			int32_t sample = ad->input_buf[i] << 16;
			ad->_input_write_sample(sample);

			if (ad->capture_channels == 1) {
				// In case input device is single channel convert it to Stereo
				ad->_input_write_sample(sample);
			}
		}

```
In case its only one channel it will write the right channel with the same data.

**Comment by SaracenOne** [comment]
@marcelofg55 Oh sorry, I didn't see that, my bad. Do you want me to merge now then?

**Comment by marcelofg55** [comment]
Yes please, I'm going to work on the PulseAudio now.

**Pull request merged**
