### PR TITLE
Modified Microphone implementation to handle only one device at a time

### PR DESCRIPTION
**Pull request by marcelofg55**
Simplified the code and added CoreAudio and PulseAudio driver code.
Still WIP.

### CODE REVIEW

**Comment by SaracenOne** [comment]
Looking good to me so far. Would you want me merge now or do you want to hang onto it for a bit longer?

**Comment by marcelofg55** [comment]
Let me work it out a bit more, I'm trying to figure out one issue with the WASAPI code.

**Comment by SaracenOne** [comment]
Got you 👌

**Comment by marcelofg55** [comment]
You may merge it now, it still lacks the device selection code, but I'll add it some other time.

**Pull request merged**
