### PR TITLE
Implemented capture device selection for PulseAudio

### PR DESCRIPTION
**Pull request by marcelofg55**
Note: Older PulseAudio seem to be buggy with this, but works with pulseaudio >= 11.1

### CODE REVIEW

**Comment by SaracenOne** [comment]
@marcelofg55 I'll try and merge this shortly, but I've actually encountered some other problems while I was rebasing to make things compatible with the new interface for writing data to vectors. I don't know if this slipped me by, but it looks like (https://github.com/SaracenOne/godot/pull/1) might have reintroduced the microphone clipping issue which was solved before, at least when I tested it under WASAPI. I narrowed down the problem to appearing in that specific commit, but I have no idea what's causing it.

Secondly, when using the device selection, it seems there is lacking functionality to resample between input devices with differing sample rates. For example, my main microphone is set to a 44100hz, while the Oculus Rift internal microphone is 48000hz, and as such, comes out sounding very high pitched. I believe I accounted for this in my initial code, but it seems to be non-functional here.

**Comment by marcelofg55** [comment]
Can you test with the Oculus Rift mic set to 44100Hz ? Does that fixes the clipping issue?

**Comment by SaracenOne** [comment]
@marcelofg55 Give me second...

**Comment by SaracenOne** [comment]
@marcelofg55 Okay, so I wasn't actually able to change the microphone settings on the Rift, they are locked to one setting (1 channel, 16bit, 48000hz). However, I did try to change my normal mic to match those settings and wasn't able to recreate the high pitch problem. The only thing I wasn't able to set was the microphone to a single channel; all the settings are locked to two channels.

One other thing I noticed though is that after changing the sample rate on my main microphone, the clipping problems would mostly go away, but changing the audio device mid use would seem to randomly introduce the clipping at seemingly completely arbitrary levels of severity. What's concerning about this is I can't discern a consistent pattern behind this behavior.

**Comment by marcelofg55** [comment]
Let me fix the rate issue, I've figured out the problem with it.

**Comment by SaracenOne** [comment]
@marcelofg55 Awesome! 👍

**Comment by marcelofg55** [comment]
Does the last commit help?

**Comment by SaracenOne** [comment]
@marcelofg55 I'm actually rebasing it at the moment since there was a very recent change to the vector array class.

**Comment by SaracenOne** [comment]
@marcelofg55 Well, I tested it, but it doesn't seem to have made any difference. Clipping is still present and the Rift mic is still high pitched :/

**Comment by SaracenOne** [comment]
@marcelofg55 By the way, do you think it would be possible to rebase onto the latest master and pull again? Our branches are currently out of sync. The only really change is that now all the vectors now include .write when writing data.

**Comment by marcelofg55** [comment]
Yeah, should I rebase it? I'm not that good rebasing :P

**Comment by SaracenOne** [comment]
@marcelofg55 What I would suggest is making a backup copy of your current audio_mic branch, delete the original, update your master branch, then pull this branch again.

**Comment by marcelofg55** [comment]
Let me try..

**Comment by SaracenOne** [comment]
@marcelofg55 Also, once you've done that, you can pull this PR again to get a rebased version of these recent changes too. That said, wait a moment since I made a very minor error with them.

**Comment by SaracenOne** [comment]
@marcelofg55 Okay, should be all good now to pull the rebased commits from this PR too.

**Comment by SaracenOne** [comment]
@marcelofg55 Sorry, I might have made it more complicated than it needs to be. You should just now be able to just backup your branch, update the master branch, and then pull everything back from your audio_mic_mf branch on your Github page since I already rebased it.

**Comment by SaracenOne** [comment]
Hopefully it will be easier to narrow down these problems once we've ensured that we're both running the exact same code.

**Comment by marcelofg55** [comment]
I've just merged it, can it be merged like this?

**Comment by SaracenOne** [comment]
@marcelofg55 If it's working with the latest version of the original master branch, then it's fine. To confirm everything's okay, the latest commit should just be a minor fix to a mistake involve indentation.

**Comment by marcelofg55** [comment]
I've just checked the "Files Changes" tab on github and it seems okay.

**Comment by SaracenOne** [comment]
@marcelofg55 Okay, so assuming everything is up to date, you should be fine. That said, the issues with clipping and pitch still remain, but it should now be a lot less hassle to work through these.

**Comment by marcelofg55** [comment]
I gtg now but I'll keep investigating those issues tomorrow. Btw, did you test this on Linux?

**Comment by SaracenOne** [comment]
@marcelofg55, not yet, I actually haven't got my Linux setup working at the moment.

**Comment by SaracenOne** [comment]
@marcelofg55 Just so you know, I managed to fix the Oculus Rift microphone issue in WASAPI. Basically, it was all down to the fact that the Rift only supports one channel; one of your commits removed the handling in WASAPI for single channel capture streams so I put it back in now it is the correct pitch. 

However, I have not yet managed to solve the reintroduced clipping issues. The only thing I can confirm is that the regression with the commit from this PR (#1 ), which broke your clipping fixes from the previous commit. I'm going to give it a rest for now, but so far I've only managed to look for two potential changes: the shift from floats to integers for the audio input buffer, and some changes to how the AudioStreamMicrophone interprets that buffer. Since you managed to fix the clipping before, if you can, try look over what could have changed in that commit which broke the previous fix.

**Comment by SaracenOne** [comment]
@marcelofg55 Good news, I think I've solved the clipping bug too (at least in WASAPI). The bug was actually caused by a couple of things which were broken in your single microphone receiver revision, including bounds checking to ensure that the stream didn't to read beyond an amount of data which has been filled in the buffer, as well as getting the arguments in the Initialize method for the AudioClient being in the wrong order, making it so that the capture buffer was too small. I also changed the stream's mixer function to make it so that the offset gets reverted back to the beginning if it the requested frames overflows whats available, which seems to handle device switching (however, clipping still occurs if the default device is changed; is there a callback for this?)

You will probably to add the bounds measurements back in for PulseAudio and CoreAudio too, but it should be pretty straightforward. Just take note of the latest commit.

**Comment by marcelofg55** [comment]
Nice work @SaracenOne !
Can you merge this PR? And then I'll re-sync my branch and update the other drivers.

**Comment by SaracenOne** [comment]
@marcelofg55 Sure thing. I just need to make sure this isn't merging more commit than necessary, in which case I might merge the commit from my end on the desktop then rather through Github.

**Comment by SaracenOne** [comment]
@marcelofg55 One problem I'm having with the mix rate commit is that it's introducing major latency into the audio capture. I need some more time to understand why it's doing that. It's likely because of how mismatched sample rates are handled.

**Comment by SaracenOne** [comment]
@marcelofg55 Okay, so since this branch seems to have had some rebasing problems, I went and committed your PulseAudio commit manually. It should be in the main branch now. I didn't merge your changes for mix rate though for the aforementioned de-sync issues, but on the other hand, it seems to work fine without them.

Due to the fact that this branch seems to have been rebased badly, my advice would just be to now create another branch based on my default audio_mic branch again to ensure everything is synced up correctly. It's already cleaned up and rebased onto the latest master. If you can add the same fixes I added to the WASAPI driver to fix single channel microphones and audio clipping, I could probably then petition to get this thing merged 👍

**Comment by marcelofg55** [comment]
Alright, I'm on it :)

**Pull request closed without merging**
